"""One-off migration: lengthen seed articles + swap broken Pexels image.
Run:  cd /app/backend && python migrate_articles.py
"""
import asyncio
import os
from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv(".env")

LONG_ARTICLES = {
    "Il potere del respiro consapevole": (
        "Il respiro è il ponte silenzioso tra il corpo e la coscienza, tra il mondo esterno e il nostro paesaggio interiore. È l'unica funzione vitale che possiamo osservare passivamente e allo stesso tempo modulare volontariamente: in questo suo carattere doppio si nasconde la chiave di innumerevoli pratiche di crescita personale e trasformazione spirituale.\n\n"
        "Le antiche tradizioni orientali hanno esplorato il respiro con una precisione che oggi la scienza sta riscoprendo. Nello yoga il pranayama è considerato la scienza dell'energia vitale: attraverso tecniche come Nadi Shodhana, Bhramari o Kapalabhati si armonizzano i canali sottili, si riequilibrano i due emisferi cerebrali, si accedono a stati di calma profonda. Nel buddhismo la consapevolezza del respiro (Anapanasati) è la prima e più diretta porta verso la meditazione.\n\n"
        "La moderna neuroscienza conferma: bastano pochi minuti di respirazione diaframmatica lenta per attivare il nervo vago, ridurre la produzione di cortisolo, aumentare la variabilità cardiaca e portare il sistema nervoso in modalità parasimpatica. Le pratiche di respirazione lenta a 6 respiri al minuto sono associate a miglioramenti misurabili nella pressione arteriosa, nella qualità del sonno e nella regolazione emotiva.\n\n"
        "Nella quotidianità il respiro consapevole diventa uno strumento potentissimo: prima di un incontro difficile, tre respiri lenti sciolgono la tensione. In un momento di rabbia, un'espirazione prolungata riporta la lucidità. Nel silenzio del mattino, cinque minuti di attenzione al respiro preparano la mente al giorno che inizia. Non serve un cuscino, un'ora libera, un maestro: serve solo ricordarsi.\n\n"
        "Il segreto è la qualità dell'attenzione. Non si tratta di respirare bene, ma di respirare consapevolmente: sentire l'aria entrare fresca dalle narici, riempire la parte bassa dell'addome, sostare nel picco della pienezza, lasciare che l'espirazione fluisca lentamente, sostare nel vuoto. Ogni ciclo è un mondo intero. Ogni respiro è un'occasione per tornare al presente.\n\n"
        "Il respiro è ponte tra volontario e involontario, tra materia e coscienza. Coltivarlo con dedizione significa coltivare la libertà interiore, la capacità di scegliere come rispondere alla vita anziché reagire meccanicamente. E questa è forse la definizione più semplice del cammino spirituale: passare dalla reazione alla risposta consapevole, un respiro alla volta."
    ),
    "Biofisica quantistica: la nuova frontiera della salute": (
        "La biofisica quantistica rappresenta un salto paradigmatico nella comprensione della vita: dalla visione puramente biochimica di corpo-macchina si passa a un modello in cui l'organismo è anzitutto un sistema informazionale coerente, capace di comunicare attraverso segnali elettromagnetici estremamente sottili.\n\n"
        "Il fisico russo Alexander Gurwitsch, già nel 1923, ipotizzò l'esistenza di emissioni luminose emesse dalle cellule viventi. Decenni dopo, il tedesco Fritz-Albert Popp confermò sperimentalmente che il DNA emette biofotoni, particelle di luce a bassissima intensità ma altamente coerenti. Ogni cellula del nostro corpo emette circa 100 biofotoni al secondo: un'orchestra silenziosa di luce che coordina i processi vitali.\n\n"
        "Cosa cambia se la salute non dipende solo dalla biochimica ma dall'informazione coerente? Cambia tutto. La malattia diventa un disordine informazionale prima ancora che biochimico. Lo stress cronico riduce la coerenza dei biofotoni. L'ambiente elettromagnetico moderno interferisce con la comunicazione cellulare. Le emozioni intense modulano la qualità del campo bio-elettromagnetico.\n\n"
        "Questa prospettiva apre la strada a terapie basate su frequenze specifiche, campi elettromagnetici coerenti, informazione trasmessa attraverso l'acqua strutturata. La ricerca del premio Nobel Luc Montagnier sulla memoria dell'acqua, gli studi del CNR italiano sui domini di coerenza di Preparata e Del Giudice, i lavori di Emilio Del Giudice sulla fisica quantistica dei sistemi viventi: tutti convergono nel mostrare che la vita è, prima di tutto, un fenomeno di coerenza quantistica.\n\n"
        "Nella pratica clinica emergente, la biorisonanza, la magnetoterapia pulsata, alcuni dispositivi che utilizzano frequenze scalari lavorano su questo piano informazionale. Non sostituiscono la medicina tradizionale ma la integrano, agendo su un livello più profondo del sintomo: il livello del campo che organizza la materia.\n\n"
        "Il paziente non è più un insieme di organi da riparare ma un campo bio-informazionale da riarmonizzare. La guarigione diventa un ritorno alla coerenza. Il medico integrato del futuro dovrà conoscere sia la biochimica sia la biofisica, sia la molecola sia il campo. È una rivoluzione silenziosa ma inevitabile, che sta ridefinendo cosa significhi essere vivi, essere sani, essere umani."
    ),
    "Somatognostica: conoscere sé stessi attraverso il corpo": (
        "La Somatognostica è una disciplina che unisce psicologia del profondo, filosofia dell'incarnazione e discipline corporee per accedere alla conoscenza di sé attraverso l'ascolto radicale del corpo. Non parla di corpo come oggetto da modellare o curare, ma come soggetto vivente che ricorda, sente, sa.\n\n"
        "Ogni tensione muscolare cronica racconta una storia personale non narrata. Le spalle rigide portano il peso di responsabilità mai deposte. Il diaframma bloccato custodisce un'emozione mai espressa. I fianchi contratti trattengono ricordi di sicurezza mai concessa. Il corpo è archivio biografico: nulla di ciò che abbiamo vissuto è veramente dimenticato, semplicemente si è depositato nei tessuti.\n\n"
        "Portare consapevolezza alle sensazioni somatiche significa entrare in dialogo con questi archivi. Non attraverso il pensiero — che è già interpretazione — ma attraverso l'ascolto puro. Un'attenzione lenta, curiosa, non giudicante che si posa su un'area del corpo e resta lì, in attesa. Prima o poi qualcosa emerge: un ricordo, un'immagine, un'emozione, un impulso di movimento.\n\n"
        "Il processo somatognostico procede per gradi. Prima si impara a percepire — molti adulti oggi hanno perso l'accesso alle proprie sensazioni interne, sostituite dal rumore mentale. Poi si impara a stare — senza fuggire dal disagio, senza fissare il piacere. Infine si impara a lasciar accadere — permettere al corpo di rilasciare, riorganizzare, integrare a suo ritmo.\n\n"
        "A differenza di molte tecniche corporee, la Somatognostica non impone posture, non prescrive esercizi standard, non guida verso stati predeterminati. Rispetta l'intelligenza intrinseca dell'organismo: sa che il corpo, se ascoltato con rispetto, trova da solo la via della propria integrazione. Il facilitatore non guarisce, accompagna. Il maestro non sa, testimonia.\n\n"
        "Nella pratica emergono spesso fenomeni sorprendenti: tremori spontanei che sciolgono traumi antichi, respirazioni che si trasformano da sole, movimenti sottili che riequilibrano le fasce muscolari, immagini interiori che rivelano nodi biografici. Nulla di tutto questo viene indotto: tutto emerge dal profondo di ciò che siamo.\n\n"
        "La Somatognostica offre un ritorno gentile alla dimensione più fondamentale dell'essere umano: il fatto di essere un corpo, non solo di averne uno. In una cultura che ci vuole sempre più cerebrali, digitali, disincarnati, questa disciplina è un atto di resistenza e amore verso la totalità di ciò che siamo."
    ),
    "L'alchimia interiore secondo la tradizione ermetica": (
        "L'alchimia non è mai stata solo trasmutazione di metalli. Dietro l'apparato simbolico di crogioli, atanor, quintessenze si nasconde una tradizione millenaria di trasformazione interiore, un'opera di individuazione spirituale che oggi la psicologia analitica di Jung ha portato in piena luce.\n\n"
        "La grande opera alchemica si articola classicamente in tre fasi cromatiche. La nigredo, opera al nero, corrisponde alla dissoluzione dell'ego, alla discesa negli inferi personali, all'incontro con l'ombra. È la fase in cui tutte le certezze si sgretolano, i sogni antichi muoiono, si tocca il fondo. Molti la vivono come depressione, crisi esistenziale, sensazione di non essere più nessuno. Ma è opera necessaria: senza dissoluzione non c'è rinascita.\n\n"
        "L'albedo, opera al bianco, è la purificazione che segue. Dopo il buio le acque tornano chiare, l'anima si separa da ciò che non le appartiene, emerge una nuova sensibilità. Simbolicamente è la luna, la femminile, l'intuizione, il ricevere. Si scoprono nuove verità, si accede a stati di grazia, si sente il proprio percorso con maggiore nitidezza. Ma non basta: l'oro spirituale non è ancora nato.\n\n"
        "La rubedo, opera al rosso, è l'integrazione finale in cui l'opposto si concilia con l'opposto: maschile e femminile, luce e ombra, cielo e terra si sposano nell'unione ermetica. L'oro alchemico è la coscienza risvegliata, capace di stare simultaneamente in tutti i piani dell'esistenza senza perdersi in nessuno. Chi ha completato l'opera cammina nel mondo ma non è del mondo, agisce senza aggrapparsi, ama senza possedere.\n\n"
        "Il testo cardine della tradizione, la Tavola Smeraldina, sintetizza la sapienza ermetica in una frase misteriosa: come sopra, così sotto. Le leggi che governano l'universo sono le stesse che governano l'anima. Trasformando sé stessi si trasforma il proprio universo. E viceversa: comprendendo il cosmo si comprende chi siamo.\n\n"
        "Ogni fase corrisponde a una crisi esistenziale che, se attraversata con coscienza, conduce a una nuova nascita. Non è un cammino lineare: si può tornare più volte alla nigredo, ogni volta a un livello più profondo. L'opera alchemica dura tutta la vita, e chi la percorre con dedizione diventa a sua volta pietra filosofale per gli altri: presenza che, semplicemente esistendo, trasforma."
    ),
    "Naturopatia: la forza vitale come principio guaritore": (
        "La naturopatia affonda le sue radici nella più antica delle intuizioni terapeutiche: esiste in ogni organismo una forza vitale intelligente, la vis medicatrix naturae, che tende costantemente al ripristino dell'equilibrio. Il naturopata non combatte il sintomo: sostiene questa forza affinché possa svolgere il suo lavoro guaritore.\n\n"
        "Questo cambio di prospettiva è rivoluzionario. La medicina sintomatica reprime la febbre, ferma la diarrea, elimina l'eruzione cutanea. La naturopatia si chiede: perché il corpo sta producendo questo sintomo? Cosa sta cercando di eliminare? Come posso sostenere il processo anziché contrastarlo? Il sintomo diventa messaggero prezioso, non nemico da abbattere.\n\n"
        "Gli strumenti della naturopatia sono antichi e naturali. La fitoterapia utilizza le piante medicinali non come farmaci a molecola singola ma come totalità che dialoga con la complessità dell'organismo. L'idroterapia sfrutta il potere del caldo, del freddo e del contrasto per stimolare la circolazione e il drenaggio. L'alimentazione consapevole rimuove i carichi tossici e fornisce nutrienti di alta qualità. La riflessologia lavora sui punti riflessi che collegano periferia e organi profondi.\n\n"
        "Il naturopata guarda il paziente nella sua totalità: non solo il sintomo ma la costituzione, la storia familiare, lo stile di vita, la dieta, il sonno, le emozioni, le relazioni. Perché la salute è un intreccio in cui tutto si tiene. Si può essere biochimicamente sani e profondamente infelici: prima o poi il corpo comunicherà l'infelicità attraverso un sintomo. Si può essere biochimicamente in disequilibrio e vivere bene se lo si comprende e lo si accompagna.\n\n"
        "L'approccio naturopatico non esclude la medicina tradizionale: la integra. Nelle emergenze, nelle patologie acute gravi, nelle chirurgie salvavita la medicina occidentale è insostituibile. Ma per la cronicità, per la prevenzione, per il benessere quotidiano, per l'accompagnamento a stili di vita più sani la naturopatia offre strumenti preziosi.\n\n"
        "Il vero naturopata è un facilitatore, non un guaritore. Non sostituisce l'intelligenza del corpo: la sostiene. Non impone un protocollo: propone un percorso adatto alla persona. Non promette guarigioni miracolose: accompagna passo dopo passo verso l'equilibrio ritrovato. Lavora con la natura, mai contro. In un tempo in cui la medicina si è spesso allontanata dal paziente per concentrarsi sulla malattia, la naturopatia riporta al centro la persona nella sua interezza vivente."
    ),
    "Meditazione mindfulness: la scienza del presente": (
        "La mindfulness ha origini profonde nella tradizione buddhista Theravada, dove per venticinque secoli è stata praticata come sati, la consapevolezza pura del momento presente. Negli anni Ottanta Jon Kabat-Zinn l'ha introdotta nel contesto medico occidentale, spogliandola dell'apparato religioso ma preservandone il cuore, e da lì è iniziato un dialogo fecondo tra saggezza contemplativa e neuroscienza.\n\n"
        "Oggi centinaia di studi rigorosi, molti dei quali con risonanza magnetica funzionale, hanno documentato gli effetti misurabili della pratica costante. Chi medita in modo continuativo per otto settimane mostra un aumento della materia grigia nell'ippocampo (memoria e apprendimento), nella corteccia prefrontale (regolazione emotiva e attenzione), nell'insula (percezione interocettiva). Simultaneamente si riduce la reattività dell'amigdala, il centro cerebrale della paura e dell'allarme.\n\n"
        "Ma cos'è concretamente la mindfulness? Non è svuotare la mente — un'idea diffusa quanto sbagliata. È il contrario: è portare piena attenzione a ciò che accade momento per momento, dentro e fuori di noi, senza aggiungere giudizio, interpretazione o resistenza. Si osservano pensieri, sensazioni, emozioni come nubi che attraversano il cielo della coscienza. Alcune sono luminose, altre tempestose: si osservano semplicemente.\n\n"
        "La pratica formale si svolge in postura seduta, con l'attenzione ancorata a un oggetto: solitamente il respiro. Quando la mente si distrae — accade di continuo — si nota gentilmente il vagare e si torna al respiro. Non c'è fallimento: la pratica È questo ritornare. Ogni volta che ci si accorge di essere altrove e si torna al presente, si rafforza la corteccia prefrontale e la capacità di attenzione volontaria.\n\n"
        "La pratica informale è forse la più trasformativa: portare mindfulness alle attività quotidiane. Mangiare consapevolmente, sentendo davvero i sapori. Camminare consapevolmente, sentendo i piedi sulla terra. Ascoltare consapevolmente, senza pensare già alla risposta. Ogni gesto ordinario può diventare porta d'ingresso al presente.\n\n"
        "Gli effetti nella vita concreta sono profondi: si reagisce meno automaticamente, si sceglie di più. Le emozioni difficili non spariscono ma perdono la loro presa. La qualità delle relazioni migliora perché si è davvero presenti. Il sonno si approfondisce, la creatività si libera, la felicità semplice del vivere torna accessibile. Non è una tecnica di rilassamento: è una rivoluzione della percezione. E chiunque, in qualsiasi condizione, può iniziare oggi, con un solo respiro consapevole."
    ),
    "Il campo morfogenetico e la memoria della natura": (
        "Il biologo britannico Rupert Sheldrake ha proposto negli anni Ottanta un'ipotesi che ha diviso profondamente la comunità scientifica: quella dei campi morfogenetici, strutture informazionali non locali che guiderebbero lo sviluppo delle forme viventi e conserverebbero la memoria della specie. Contestata da alcuni, esplorata da altri, questa teoria offre una prospettiva affascinante sull'ereditarietà, sulla memoria collettiva e sui fenomeni di apprendimento.\n\n"
        "L'intuizione di partenza è semplice: la genetica da sola non spiega come mai una cellula uovo, che contiene esattamente lo stesso DNA di tutte le altre cellule dell'organismo adulto, riesca a differenziarsi in centinaia di tipi cellulari organizzati in forme così precise. Il DNA fornisce le istruzioni molecolari, ma chi coordina lo sviluppo tridimensionale nel tempo? Sheldrake ipotizza campi organizzatori che agiscono per risonanza con forme simili preesistenti.\n\n"
        "Applicato agli organismi, ciò significa che ogni specie è modellata non solo dai geni ma da un campo di informazione che si è formato attraverso l'evoluzione. Ogni nuovo individuo entra in risonanza con la memoria della propria specie. E ogni esperienza nuova, se ripetuta, modifica il campo, rendendo più facile lo stesso apprendimento nelle generazioni successive.\n\n"
        "Vi sono osservazioni intriganti che supportano l'ipotesi. Cristallizzazioni chimiche di sostanze nuove diventano progressivamente più veloci in laboratori diversi nel mondo, come se il campo del cristallo si stesse consolidando. Comportamenti appresi da alcuni animali sembrano diffondersi ad altri della stessa specie geograficamente isolati. Enigmi come le migrazioni degli uccelli o l'orientamento dei salmoni potrebbero trovare qui un tassello di spiegazione.\n\n"
        "Per la salute umana, il modello dei campi morfogenetici apre riflessioni potenti. I traumi trans-generazionali documentati dall'epigenetica trovano qui una possibile cornice esplicativa più ampia. Le costellazioni familiari sviluppate da Bert Hellinger operano proprio su questo piano di informazione condivisa che collega i membri di una famiglia oltre lo spazio e il tempo.\n\n"
        "Al di là della verifica scientifica, che è ancora in corso, l'idea che la natura ricordi e che noi siamo parte di questa memoria vivente ha un impatto esistenziale profondo. Ci ricorda che non siamo individui isolati ma nodi di una rete di relazioni che si estende all'intero regno vivente. Ogni scelta che facciamo, ogni pratica che coltiviamo, aggiunge una goccia al fiume della memoria collettiva. Curarsi non è mai un fatto solo personale: è un contributo al campo che tutti condividiamo."
    ),
    "Yoga e le otto membra di Patanjali": (
        "Circa duemila anni fa, il saggio Patanjali compose gli Yoga Sutra, un testo di appena 196 aforismi che ancora oggi rappresenta la mappa più completa del cammino yogico. Al centro della sua opera troviamo l'ashtanga, gli otto rami dello yoga, un percorso progressivo che va dall'etica quotidiana all'unione mistica con l'assoluto.\n\n"
        "Il primo ramo, yama, riguarda l'etica relazionale: non nuocere (ahimsa), verità (satya), non rubare (asteya), moderazione (brahmacharya), non attaccamento (aparigraha). Sono i cinque grandi comandamenti universali dello yoga: nessuna pratica interiore può prosperare su fondamenta relazionali malsane.\n\n"
        "Il secondo ramo, niyama, è la disciplina personale: purezza, contentezza, ardore ascetico, studio di sé, abbandono al divino. Sono i cinque pilastri della coltivazione interiore. Chi non purifica il proprio spazio interiore non può accogliere la conoscenza.\n\n"
        "Il terzo ramo, asana, è la postura fisica. Solo qui — al terzo gradino — entra ciò che l'Occidente chiama yoga: il lavoro sul corpo. Patanjali dedica alle asana un solo aforisma: stabilità e comodità. La postura yogica è quella in cui si può stare a lungo senza sforzo, condizione per praticare i rami successivi.\n\n"
        "Il quarto ramo, pranayama, è il controllo del prana attraverso il respiro. Tecniche specifiche di respirazione bilanciata, alternata, prolungata affinano il sistema nervoso e preparano la mente alla concentrazione.\n\n"
        "Il quinto ramo, pratyahara, è il ritiro dei sensi. Come una tartaruga ritira le zampe nel proprio guscio, così il praticante impara a distogliere l'attenzione dagli stimoli esterni per rivolgerla all'interno. È il ponte tra pratica esteriore e pratica interiore.\n\n"
        "Il sesto ramo, dharana, è la concentrazione: fissare l'attenzione su un unico oggetto — un mantra, un simbolo, un punto del corpo, il respiro — resistendo alle distrazioni. È la base della meditazione vera.\n\n"
        "Il settimo ramo, dhyana, è la meditazione fluida: quando la concentrazione diventa continua, senza interruzioni, come olio che si versa. Il meditante e l'oggetto della meditazione iniziano a fondersi.\n\n"
        "L'ottavo ramo, samadhi, è l'unione: la dissoluzione totale della dualità osservatore-osservato in un'unica consapevolezza pura. È lo scopo ultimo dello yoga, il ritorno alla propria natura originaria, la liberazione dalla sofferenza dell'ego separato.\n\n"
        "Gli otto rami non sono tappe sequenziali rigide ma dimensioni intrecciate della vita yogica. Si praticano contemporaneamente, ognuno rafforzando gli altri. Chi coltiva questa via non fa ginnastica orientale: percorre un sentiero di trasformazione totale che tocca corpo, respiro, mente, cuore e spirito insieme."
    ),
    "Medicina integrata: unire tradizioni per il paziente": (
        "La medicina integrata non è né alternativa né complementare: è l'orizzonte in cui il rigore scientifico della biomedicina si unisce alla saggezza olistica delle medicine tradizionali per servire il paziente nella sua interezza. Non contrappone paradigmi: li fa dialogare.\n\n"
        "Il paziente contemporaneo vive spesso una divisione dolorosa. Da un lato la medicina convenzionale, potente nella diagnosi e nell'emergenza ma spesso ridotta a protocolli standard, tempi brevi, focus sul sintomo isolato. Dall'altro le medicine tradizionali — agopuntura, omeopatia, ayurveda, medicina antroposofica — con una visione più ampia dell'essere umano ma talvolta prive di verifica sperimentale rigorosa. La medicina integrata li fa incontrare per il bene del paziente.\n\n"
        "L'evidenza scientifica accumulata è imponente. L'agopuntura è oggi raccomandata dall'Organizzazione Mondiale della Sanità in oltre cento condizioni, dal dolore cronico all'infertilità funzionale. La mindfulness è integrata in ospedali di tutto il mondo per la gestione dell'ansia, della depressione ricorrente, del dolore. Alcune preparazioni fitoterapiche hanno dimostrato efficacia clinica in trial randomizzati controllati.\n\n"
        "L'approccio integrato mette al centro la persona con protocolli personalizzati. Un paziente con emicrania cronica non riceverà solo antidolorifici: si valuteranno la sua alimentazione, la qualità del sonno, i livelli di stress, la postura cervicale, eventuali sensibilità alimentari, i pattern respiratori. Si combineranno strategie farmacologiche mirate, agopuntura, riequilibrio nutrizionale, tecniche di rilassamento, terapia manuale.\n\n"
        "La sfida principale è culturale. Formare medici integrati richiede curricula universitari che aprano al pluralismo terapeutico senza perdere il rigore metodologico. Servono ospedali che ospitino sotto lo stesso tetto competenze diverse. Servono sistemi sanitari che rimborsino terapie integrate quando dimostrate efficaci. Servono pazienti che siano informati e attivi partner della propria cura.\n\n"
        "Le esperienze pioniere esistono già: la Cleveland Clinic, il Memorial Sloan Kettering, alcuni centri europei e italiani stanno costruendo modelli di eccellenza. In Italia la medicina integrata cresce lentamente ma inesorabilmente, sostenuta da un numero crescente di medici formati e di pazienti che chiedono un approccio più ampio.\n\n"
        "Il futuro della medicina è integrativo. Non per moda o ideologia, ma perché il paziente lo chiede, l'evidenza lo supporta, la complessità della salute contemporanea — con la crescente incidenza di malattie croniche legate a stile di vita, ambiente e stress — lo richiede. Una medicina che unisce anziché dividere è, semplicemente, medicina migliore."
    ),
    "Psicologia analitica: l'ombra e l'individuazione": (
        "Carl Gustav Jung, allievo di Freud e poi suo dissidente, ha dedicato la sua vita a mappare il territorio dell'inconscio con una profondità che nessuno prima e pochi dopo hanno raggiunto. Al centro della sua opera si trova un concetto tanto semplice quanto trasformativo: l'individuazione, il processo attraverso cui una persona diventa pienamente sé stessa integrando le parti separate della propria psiche.\n\n"
        "L'ombra è il primo grande incontro del cammino junghiano. Contiene tutto ciò che l'ego ha rifiutato: aggressività non ammessa, paure celate, desideri censurati, doni non riconosciuti. Ogni persona, per adattarsi alla famiglia e alla società, ha dovuto reprimere aspetti di sé. Questi aspetti non spariscono: si depositano nell'inconscio personale e da lì influenzano le nostre reazioni, i nostri giudizi, le nostre relazioni.\n\n"
        "Non integrare l'ombra significa proiettarla sugli altri. Chi non riconosce la propria aggressività la vedrà ovunque negli altri. Chi non ammette la propria vulnerabilità disprezzerà i vulnerabili. Chi ha soffocato il proprio desiderio invidierà chi lo vive apertamente. Il mondo diventa uno specchio distorto, popolato dei nostri fantasmi non riconosciuti.\n\n"
        "Riconoscere l'ombra richiede coraggio. Significa ammettere di essere capaci anche di ciò che disprezziamo, portatori anche di ciò che neghiamo, in ombra come in luce. Ma proprio questo riconoscimento libera enormi quantità di energia psichica prima consumata dalla repressione. L'ombra integrata non è più un fantasma: diventa risorsa, potenza, vitalità.\n\n"
        "Oltre l'ombra il cammino incontra altre figure archetipiche: l'anima nell'uomo, l'animus nella donna, il vecchio saggio, la grande madre, e infine il Sé — quel nucleo di totalità che precede e trascende l'ego, verso cui l'individuazione tende. L'individuazione non è auto-realizzazione narcisistica: è realizzazione del Sé, ovvero apertura alla dimensione trans-personale che ci abita.\n\n"
        "Il lavoro analitico junghiano procede attraverso strumenti raffinati: analisi dei sogni, che portano messaggi diretti dall'inconscio; immaginazione attiva, dialogo cosciente con le figure interiori; attenzione alle sincronicità, quelle coincidenze significative che sembrano tessute dal senso. Non è un lavoro breve: richiede anni, talvolta decenni. Ma trasforma non solo chi lo compie: attraverso di lui trasforma il campo in cui vive.\n\n"
        "Divenire sé stessi è opera di una vita. Non un traguardo da raggiungere ma un movimento continuo di scoperta, integrazione, apertura. Jung diceva che meglio essere interi che perfetti. L'individuazione è la strada verso questa interezza dolorosa, splendida, autenticamente umana."
    ),
    "Alimentazione consapevole: cibo come informazione": (
        "Il cibo non è mai stato solo carburante. Ogni tradizione sapienziale del pianeta ha riconosciuto che ciò che mangiamo diventa parte di ciò che siamo, non solo a livello fisico ma anche energetico ed emotivo. L'alimentazione consapevole recupera questa antica saggezza e la unisce alle scoperte più avanzate della nutrizione moderna.\n\n"
        "La medicina tradizionale cinese classifica gli alimenti secondo qualità energetiche: yin (rinfrescanti) o yang (riscaldanti), secondo cinque sapori corrispondenti a cinque organi, secondo il colore che dialoga con specifiche funzioni. Non esistono cibi buoni o cattivi in assoluto: esistono cibi appropriati alla stagione, alla costituzione, al momento della vita di una persona. L'ayurveda indiana parla di tre dosha — vata, pitta, kapha — e adatta l'alimentazione al biotipo individuale.\n\n"
        "La scienza moderna conferma da direzioni diverse. La nutrigenomica studia come specifici nutrienti attivino o silenzino determinati geni. Il microbioma intestinale, ecosistema di trilioni di batteri, viene modellato quotidianamente da ciò che mangiamo e a sua volta influenza umore, immunità, metabolismo. I polifenoli delle piante, le fibre prebiotiche, gli acidi grassi omega-3 sono informazioni chimiche che orchestrano la nostra biologia.\n\n"
        "Ma consapevolezza alimentare significa molto più della scelta degli ingredienti giusti. Significa anche come mangiamo. Uno stesso cibo, consumato di fretta davanti allo schermo con la mente altrove, produce effetti diversi rispetto allo stesso cibo consumato lentamente, in presenza, con gratitudine. Il sistema nervoso enterico — il cervello dell'intestino — riceve segnali profondamente diversi in queste due modalità.\n\n"
        "Mangiare consapevolmente significa scegliere, masticare lentamente, riconoscere fame e sazietà reali distinguendole dai bisogni emotivi. Significa domandarsi: questo alimento mi nutre davvero? Da dove viene? Chi lo ha coltivato? Con quali intenzioni è stato preparato? Ogni pasto diventa un momento di riconnessione: alla natura, alla comunità che ci sostiene, al proprio corpo.\n\n"
        "L'alimentazione consapevole non è una dieta rigida ma un'arte flessibile. Si adatta alle stagioni, agli stati emotivi, alle fasi della vita. Rispetta le tradizioni culturali senza esserne prigioniera. Si apre alla novità senza abbandonare il buonsenso. E soprattutto si costruisce nel tempo, un pasto alla volta, con pazienza e curiosità.\n\n"
        "Diventiamo ciò che digeriamo, non solo ciò che mangiamo. Il pasto è cerimonia sacra travestita da atto quotidiano. Riscoprirlo come tale significa riscoprire il corpo come tempio, la terra come madre, la vita come dono continuo che merita gratitudine ad ogni boccone."
    ),
    "Filosofia perenne: l'unità dietro le tradizioni": (
        "Aldous Huxley coniò negli anni Quaranta l'espressione philosophia perennis, filosofia perenne, per indicare quel nucleo di sapienza che ricorre in tutte le grandi tradizioni spirituali dell'umanità nonostante le differenze di linguaggio, cultura, epoca storica. Non è sincretismo superficiale: è il riconoscimento che sotto le forme diverse c'è una comune esperienza dell'assoluto.\n\n"
        "Le costanti che emergono sono impressionanti. La realtà ultima, chiamata Brahman nell'Induismo, Dharmakaya nel Buddhismo, Tao nel Taoismo, Ein Sof nella Kabbalah ebraica, Deo assoluto nella mistica cristiana, Al-Haqq nel Sufismo islamico. Non un dio antropomorfo ma la sorgente ultima da cui tutto emana e a cui tutto ritorna.\n\n"
        "Il sé profondo — atman, buddha-nature, punto vergine dell'anima, scintilla divina — è considerato in tutte queste tradizioni consustanziale alla realtà ultima. Il fine dell'esistenza è realizzare questa identità profonda: conoscere sé stessi significa conoscere Dio, conoscere Dio significa conoscere sé stessi. Non è metafora poetica ma esperienza mistica documentata da migliaia di testimoni in tutte le culture.\n\n"
        "Le vie per realizzare questa unione condividono strutture simili. Una fase di purificazione etica e ascetica. Una fase di illuminazione contemplativa. Una fase di unione trasformativa. Vedanta, Sufismo, misticismo cristiano, buddismo Mahayana, Kabbalah ebraica descrivono lo stesso arco con lessici diversi. Chi è entrato profondamente in una tradizione riconosce i propri passi negli scritti degli altri.\n\n"
        "Alcuni testi sono diventati patrimonio universale. La Bhagavad Gita indiana, i Sutra di Patanjali, il Tao Te Ching, i Vangeli, le opere di Meister Eckhart, di Rumi, di San Giovanni della Croce, di Ibn Arabi, del Chuang Tzu: parlano la stessa lingua ultima sotto codici diversi. Leggerli tutti — non superficialmente ma in profondità — porta al medesimo silenzio contemplativo.\n\n"
        "Questo riconoscimento non annulla le tradizioni: le onora. Ogni tradizione è una porta unica sul mistero, con la propria bellezza, i propri metodi, i propri maestri. Attraversare una porta con dedizione porta comunque all'unico spazio interiore. Il rispetto per la propria via non richiede il disprezzo delle altre: al contrario, chi ha visto la meta riconosce ovunque altri viandanti.\n\n"
        "La filosofia perenne è particolarmente preziosa nel nostro tempo, segnato da fondamentalismi contrapposti e da un materialismo che ha perso le sue radici. Ci ricorda che l'umanità ha un patrimonio spirituale comune, che i valori di compassione, verità, giustizia non appartengono a nessuna singola cultura ma alla condizione umana in sé. In un mondo diviso, la filosofia perenne è ponte silenzioso che unisce ciò che le apparenze separano."
    ),
    "Crescita personale: la responsabilità della propria vita": (
        "La crescita personale non è un manuale di trucchi motivazionali ma una trasformazione profonda del rapporto che abbiamo con la nostra esistenza. Il suo punto di svolta arriva quando smettiamo di essere spettatori lamentosi della vita che ci accade e diventiamo autori consapevoli della vita che scegliamo.\n\n"
        "Il primo passo è il più difficile: assumere la piena responsabilità della propria esperienza. Non significa credere di essere la causa di tutto ciò che ci accade — questo sarebbe onnipotenza infantile. Significa riconoscere che, qualunque cosa accada, possiamo scegliere come rispondere. Tra lo stimolo e la nostra reazione esiste sempre uno spazio, per quanto piccolo. In quello spazio si trova la nostra libertà.\n\n"
        "Viktor Frankl ha vissuto Auschwitz e ne ha tratto una sapienza che nessuna teoria potrebbe raggiungere: gli hanno tolto tutto tranne l'ultima libertà, quella di scegliere il proprio atteggiamento di fronte alle circostanze. Se questa libertà è stata trovata in un campo di concentramento, quanto più possiamo trovarla nella vita ordinaria? La crescita personale inizia quando accettiamo di esercitare questa libertà anziché scusarcene.\n\n"
        "Il secondo passo è imparare a distinguere ciò che dipende da noi da ciò che non dipende da noi. Epitteto lo insegnava già duemila anni fa: se dirigi le tue energie su ciò che non controlli, ti condanni alla frustrazione. Se ti concentri su ciò che controlli — i tuoi pensieri, le tue parole, le tue azioni — accedi a un potere reale, silenzioso, trasformativo.\n\n"
        "Il terzo passo è la coerenza tra valori e azioni. La maggior parte della sofferenza personale nasce dalla dissonanza tra ciò che sappiamo essere giusto e ciò che effettivamente facciamo. Crescere significa progressivamente allineare l'agire al sentire profondo. Non serve la perfezione — è irraggiungibile — serve la direzione. Ogni piccolo gesto coerente è un mattone della persona che stiamo diventando.\n\n"
        "Il quarto passo è coltivare la consapevolezza quotidiana. Senza attenzione ai propri stati interni si vive in automatico, guidati da schemi ereditati e non scelti. Meditazione, journaling, dialogo profondo con persone di fiducia, terapia personale: qualunque strumento ci permetta di vederci con occhi lucidi accelera il cammino.\n\n"
        "Il quinto passo è servire qualcosa di più grande di sé. Paradossalmente la piena realizzazione personale arriva quando smettiamo di puntare solo su di noi. Un lavoro che serve, una relazione che nutre, una causa che va oltre l'ego: sono queste le acque in cui la crescita personale si compie.\n\n"
        "Ogni giorno è occasione per praticare consapevolezza, autenticità e coraggio. Nessun maestro esterno può fare al posto nostro questo lavoro. Ma con costanza, umiltà e amore per sé, ogni persona può diventare la versione più piena e libera di ciò che è. E questa, forse, è la più grande forma di rispetto verso il dono della vita."
    ),
}


async def migrate():
    c = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = c[os.environ["DB_NAME"]]
    # Fix quantum physics image with a working Unsplash URL
    await db.articles.update_one(
        {"category": "Fisica quantistica"},
        {"$set": {"image_url": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800"}},
    )
    print("Fixed image for Fisica quantistica")

    # Also make sure ALL articles have an image (fallback to category default)
    fallback = {
        "Crescita personale": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
        "Spirituale": "https://images.unsplash.com/photo-1600181982553-ce7d36051c01?w=800",
        "Fisica quantistica": "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800",
        "Meditazione": "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800",
        "Discipline orientali": "https://images.unsplash.com/photo-1545389336-cf090694435e?w=800",
        "Naturopatia": "https://images.unsplash.com/photo-1612703508477-00e02a9b170c?w=800",
        "Psicologia": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800",
        "Medicina Integrata": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800",
        "Filosofia": "https://images.unsplash.com/photo-1519791883288-dc8bd696e667?w=800",
        "Nutrizione": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800",
        "Somatognostica": "https://images.unsplash.com/photo-1588406320565-9fa6d9901d1d?w=800",
        "Video": "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800",
    }
    async for a in db.articles.find({"$or": [{"image_url": None}, {"image_url": ""}, {"image_url": {"$exists": False}}]}, {"_id": 0, "id": 1, "category": 1}):
        img = fallback.get(a["category"], fallback["Meditazione"])
        await db.articles.update_one({"id": a["id"]}, {"$set": {"image_url": img}})
        print(f"Filled missing image for {a['category']}")

    # Lengthen articles
    updated = 0
    for title, long_summary in LONG_ARTICLES.items():
        r = await db.articles.update_one({"title": title}, {"$set": {"summary": long_summary}})
        if r.modified_count:
            updated += 1
    print(f"Lengthened {updated}/{len(LONG_ARTICLES)} articles")
    c.close()


if __name__ == "__main__":
    asyncio.run(migrate())
