"""Seed articles from Citazioni.docx.

Structure per article:
- Title: LLM-generated (evocative, based on quote theme)
- Summary body:
    line 1:  «Citazione» — Autore   (as italic-like opening block)
    blank line
    Commento (from doc, unchanged)
    blank line
    ~400 words of expansion generated by LLM
- image_url: themed by author category

Total: ~46 citations.
"""

import asyncio, json, os, re, uuid, hashlib
from datetime import datetime, timezone

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv("/app/backend/.env")

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY")
MONGO_URL = os.environ["MONGO_URL"]
DB_NAME = os.environ["DB_NAME"]

CATEGORIES = [
    "Crescita personale", "Spirituale", "Fisica quantistica", "Meditazione",
    "Discipline orientali", "Naturopatia", "Psicologia", "Medicina Integrata",
    "Filosofia", "Nutrizione", "Somatognostica",
]

# ---------------- Author -> category + image mapping ----------------

IMG = {
    "cosmos": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=70",
    "quantum": "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200&auto=format&fit=crop&q=70",
    "wave": "https://images.unsplash.com/photo-1502908557874-0d68a1f7db83?w=1200&auto=format&fit=crop&q=70",
    "philosophy": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&auto=format&fit=crop&q=70",
    "statue": "https://images.unsplash.com/photo-1552083375-1447ce886485?w=1200&auto=format&fit=crop&q=70",
    "meditation": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&auto=format&fit=crop&q=70",
    "yoga": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&auto=format&fit=crop&q=70",
    "light": "https://images.unsplash.com/photo-1502139214982-d0ad755818d8?w=1200&auto=format&fit=crop&q=70",
    "mind": "https://images.unsplash.com/photo-1531177071211-e34344c6dc26?w=1200&auto=format&fit=crop&q=70",
    "body": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=70",
    "forest": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&auto=format&fit=crop&q=70",
    "water": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200&auto=format&fit=crop&q=70",
    "sunset": "https://images.unsplash.com/photo-1495604936166-44dc5e2b2437?w=1200&auto=format&fit=crop&q=70",
    "hands": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&auto=format&fit=crop&q=70",
    "mandala": "https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=1200&auto=format&fit=crop&q=70",
    "network": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=70",
    "heart": "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=1200&auto=format&fit=crop&q=70",
    "energy": "https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1200&auto=format&fit=crop&q=70",
    "dance": "https://images.unsplash.com/photo-1547153760-18fc86324498?w=1200&auto=format&fit=crop&q=70",
}

AUTHOR_MAP = {
    "Roberto Fabbroni":            ("Medicina Integrata", "energy"),
    "David Bohm":                  ("Fisica quantistica", "quantum"),
    "Albert Einstein":             ("Fisica quantistica", "cosmos"),
    "Wolfgang Pauli":              ("Fisica quantistica", "quantum"),
    "Erwin Schrödinger":           ("Fisica quantistica", "wave"),
    "Werner Heisenberg":           ("Fisica quantistica", "wave"),
    "Carl Gustav Jung":            ("Psicologia", "mandala"),
    "Frederick Perls":             ("Psicologia", "mind"),
    "Perls":                       ("Psicologia", "mind"),
    "Antonio Damasio":             ("Psicologia", "mind"),
    "Maurice Merleau-Ponty":       ("Filosofia", "body"),
    "Friedrich Nietzsche":         ("Filosofia", "statue"),
    "Alexander Lowen":             ("Psicologia", "energy"),
    "Viktor Frankl":               ("Psicologia", "light"),
    "Edgar Cayce":                 ("Spirituale", "light"),
    "Sant'Agostino":               ("Filosofia", "philosophy"),
    "Aristotele":                  ("Filosofia", "statue"),
    "Gregory Bateson":             ("Filosofia", "network"),
    "Fritjof Capra":               ("Filosofia", "forest"),
    "Osho":                        ("Spirituale", "meditation"),
    "Andrew Taylor Still":         ("Medicina Integrata", "body"),
    "Fritjof Capra e Pier Luigi Luisi": ("Filosofia", "forest"),
    "Pierre Teilhard de Chardin":  ("Spirituale", "cosmos"),
    "Ken Wilber":                  ("Filosofia", "network"),
    "Ervin Laszlo":                ("Filosofia", "cosmos"),
    "Rumi":                        ("Spirituale", "water"),
    "Tommaso Campanella":          ("Filosofia", "philosophy"),
    "Edgar Morin":                 ("Filosofia", "network"),
    "Morin":                       ("Filosofia", "network"),
    "B.K.S. Iyengar":              ("Discipline orientali", "yoga"),
    "Schrödinger":                 ("Fisica quantistica", "wave"),
}


def author_meta(author: str) -> tuple[str, str]:
    for key, (cat, img_key) in AUTHOR_MAP.items():
        if key.lower() in author.lower():
            return cat, IMG[img_key]
    return "Filosofia", IMG["philosophy"]


# ---------------- All citations ----------------

CITATIONS = [
    # Roberto Fabbroni
    ("Roberto Fabbroni",
     "Riconnettere Corpo, Mente e Anima-Spirito per recuperare Salute e Benessere in una visione sistemica e unitaria che porti alla guarigione.",
     "Fabbroni, direttore scientifico dell'Istituto di Biofisica Informazionale, sintetizza il cuore del suo approccio: la guarigione non è la soppressione di un sintomo, ma il ripristino della connessione tra le dimensioni dell'essere umano. La sua visione è pienamente sistemica: corpo, mente e anima-Spirito non sono livelli separati, ma un'unica rete di relazioni in cui la disarmonia di una parte si ripercuote sull'intero sistema."),
    ("Roberto Fabbroni",
     "Recupero di una Visione Sistemica in cui corpo, mente, anima-Spirito ed energia siano correlati.",
     "Questa frase esplicita il fondamento epistemologico del suo lavoro: l'essere umano è un sistema complesso in cui la dimensione energetica funge da ponte tra materia e spirito. In termini evolutivi, questa prospettiva invita a superare ogni dualismo per abbracciare una comprensione integrata della vita."),
    ("Roberto Fabbroni",
     "La creazione è un fatto voluto e avviene attraverso l'intenzione e tutto ciò che è creato segue delle regole fisico-matematiche o leggi universali.",
     "Fabbroni unisce la dimensione intenzionale (spirituale) con quella delle leggi fisico-matematiche, suggerendo che l'evoluzione non è né puramente materiale né puramente spirituale, ma un processo in cui coscienza e struttura si co-determinano. È una visione in cui l'anima non è un'eccezione alle leggi della natura, ma la loro espressione più profonda."),
    ("Roberto Fabbroni",
     "Quale altro campo d'azione potrebbe avere la nostra anima per comunicare con noi se non il nostro corpo?",
     "Questa domanda retorica è una delle formulazioni più chiare del principio di incarnazione in ottica sistemica. L'anima non comunica \"dall'esterno\", ma attraverso il corpo: ogni sensazione, emozione e sintomo è un messaggio del campo unificato che chiamiamo persona."),

    # Fisici (prima sezione)
    ("David Bohm",
     "Per \"pensiero\" io intendo tutto l'insieme – pensato, sentito, il corpo, l'intera società coi suoi pensieri condivisi – è tutto un unico processo.",
     "Il fisico statunitense, allievo di Oppenheimer, elabora una visione in cui pensiero, corpo e società non sono entità separate ma aspetti di un unico flusso. La sua teoria dell'ordine implicato suggerisce che la frammentazione che percepiamo è un'illusione dovuta alla nostra modalità di osservazione, non una proprietà della realtà."),
    ("David Bohm",
     "Le parti vengono considerate in connessione immediata, dalla quale dipende il loro rapporto dinamico, in maniera irriducibile, con lo stato dell'intero sistema... Si giunge così alla nozione di totalità priva di discontinuità che nega la classica idea dell'analizzabilità del mondo in parti aventi un'esistenza separata e indipendente.",
     "Questa è forse la formulazione più rigorosa del principio sistemico applicato alla fisica. Bohm mostra che l'idea stessa di \"parti separate\" è un'astrazione: nell'universo reale, ogni cosa è in relazione costitutiva con il tutto. Applicato all'essere umano, questo significa che corpo, mente e anima non sono \"componenti\" ma dimensioni di un'unica totalità in relazione."),
    ("Albert Einstein",
     "Corpo e anima non sono due cose diverse, ma solo due modi di percepire la stessa cosa.",
     "Einstein, padre della relatività, esprime in una frase folgorante ciò che le neuroscienze contemporanee confermano: la distinzione tra corpo e anima è una costruzione della nostra percezione, non una realtà ontologica. In una prospettiva evolutiva, questa intuizione apre la strada a una comprensione dell'essere umano come unità psicofisica."),
    ("Wolfgang Pauli",
     "Contro la rigorosa separazione delle attività dello spirito umano in camere stagne, in atto dal diciassettesimo secolo, io considero l'aspirazione a un superamento dei contrasti, quale potrebbe essere una sintesi della comprensione razionale con l'esperienza mistica unitaria, come il mito espresso o inespresso di questo nostro tempo.",
     "Pauli, premio Nobel per la fisica e collaboratore di Jung, denuncia la frammentazione del sapere come una patologia storica. La sua aspirazione a una \"sintesi\" tra razionalità scientifica ed esperienza mistica è un programma evolutivo: superare la separazione tra le \"due culture\" per approdare a una conoscenza integrata della realtà."),
    ("Erwin Schrödinger",
     "Il numero totale di menti è solo uno... esiste solo una mente.",
     "Il padre della meccanica ondulatoria, nella sua riflessione filosofica, giunge a una conclusione radicalmente monista: la molteplicità delle menti individuali è un'illusione di superficie. In ottica sistemica, questa intuizione suggerisce che l'evoluzione della coscienza non è un processo di accumulo individuale, ma di riconoscimento di un'unità fondamentale che precede ogni separazione."),

    # Maestri spirituali e terapeuti (sez. 1-10)
    ("Carl Gustav Jung",
     "Lo spirito è il corpo vivente visto dall'interno, e il corpo la manifestazione esteriore dello spirito vivente – e corpo e spirito sono in realtà un tutto unico.",
     "Jung ribalta la tradizionale gerarchia tra spirito e materia: non esiste uno spirito separato che \"abita\" un corpo, ma due facce della stessa medaglia. In ottica sistemica, questa intuizione è rivoluzionaria perché elimina alla radice ogni dualismo, aprendo la strada a una comprensione dell'essere umano come totalità integrata in cui ogni dimensione è espressione dell'altra."),
    ("Frederick Perls",
     "L'uomo è un organismo vivente: alcuni dei suoi aspetti sono chiamati corpo, mente e anima. Se definiamo corpo come somma di cellule, la mente come somma di percezioni e di pensieri, e l'anima come somma di emozioni... ci rendiamo conto di quanto artificiali e quanto lontane dalla realtà siano queste divisioni.",
     "Perls smaschera la frammentazione come un artificio del pensiero analitico. La sua critica è profondamente sistemica: le \"parti\" non esistono se non nell'astrazione di chi le separa. L'organismo umano è un tutto vivente che si esprime attraverso aspetti che chiamiamo corpo, mente e anima, ma che non hanno esistenza separata."),
    ("Antonio Damasio",
     "L'anima respira attraverso il corpo, e la sofferenza, che nasce dalla pelle o da un'immagine mentale, accade nella carne.",
     "Il neuroscienziato portoghese traduce in linguaggio scientifico ciò che Jung e Perls intuivano filosoficamente. Non c'è esperienza psichica che non passi attraverso il corpo, e non c'è evento corporeo che non abbia una risonanza psichica. La \"saggezza sistemica\" di Bateson trova qui la sua conferma empirica: il confine tra soma e psiche è una costruzione che la realtà dell'esperienza umana continuamente smentisce."),
    ("Maurice Merleau-Ponty",
     "Io non sono di fronte al mio corpo, ma sono nel mio corpo, o meglio sono il mio corpo.",
     "Il filosofo francese rovescia la prospettiva cartesiana: il corpo non è un oggetto che possiedo, ma il soggetto stesso della mia esistenza. In ottica sistemica, questa affermazione è cruciale perché riconosce che la conoscenza e l'esperienza emergono dall'essere incarnati, non da una mente disincarnata che osserva il mondo dall'esterno."),
    ("Friedrich Nietzsche",
     "Corpo io sono e anima – così parla il fanciullo. ...corpo io sono in tutto e per tutto, e null'altro; e anima non è altro che una parola per indicare qualcosa del corpo.",
     "Nietzsche anticipa di un secolo le neuroscienze contemporanee. La sua provocazione è un invito a superare ogni dualismo: ciò che chiamiamo \"anima\" è una dimensione del corpo, non un'entità separata. In una visione sistemica, questa affermazione ci ricorda che ogni tentativo di gerarchizzare le dimensioni umane è destinato a fallire."),
    ("Alexander Lowen",
     "La spiritualità è lo spirito divino che agisce nel corpo.",
     "Lowen, allievo di Wilhelm Reich, ha dedicato la vita a dimostrare che la spiritualità non è un'astrazione mentale ma un'esperienza corporea. Quando mente e corpo vengono separati, la spiritualità diventa una \"fede\" intellettuale; quando vengono ricongiunti, diventa \"forza vitale\". La sua definizione è sistemica perché colloca il sacro nell'immanenza del corpo vivente, non in una trascendenza separata."),
    ("Viktor Frankl",
     "Solo la persona spirituale viene a fondare la unità e totalità dell'ente umano. E la fonda come totalità corporeo-animico-spirituale. Mai potremo insistere troppo su questo: questa triple totalità è ciò che costituisce l'uomo intero.",
     "Frankl, fondatore della logoterapia, elabora una visione sistemica dell'essere umano come unità corporeo-animico-spirituale. La dimensione spirituale (noetica) non è un \"livello superiore\" separato, ma la dimensione che unifica e dà senso all'intera totalità. L'evoluzione umana, in questa prospettiva, consiste nel riconoscere e realizzare questa unità."),
    ("Edgar Cayce",
     "Il sé spirituale è vita, l'attività del mentale e del fisico è dell'anima – e quindi un'anima-corpo.",
     "Il mistico americano, noto come il \"profeta dormiente\", esprime una visione in cui spirito, mente e corpo non sono tre sostanze ma tre funzioni di un'unica realtà. Lo spirito è la vita stessa; la mente è l'attività che la esprime; il corpo è il suo veicolo. L'evoluzione, in questa prospettiva, è il processo attraverso cui questa unità diventa consapevole di sé."),
    ("Sant'Agostino",
     "L'uomo deve essere inteso come una unità sostanziale complessa, le cui parti (corpus et anima, corpus et spiritus, anima et spiritus) si suppongono mutuamente.",
     "Agostino, spesso erroneamente associato a una visione dualista, matura nel corso della sua opera una concezione dell'essere umano come unità sostanziale. Anima e corpo non sono due sostanze separate ma \"co-principi\" che si implicano a vicenda. In ottica sistemica, questa è una delle prime formulazioni dell'idea che le \"parti\" di un sistema non hanno esistenza indipendente dal tutto."),
    ("Aristotele",
     "Non c'è bisogno di cercare se l'anima e il corpo formano un'unità.",
     "Con la celebre metafora della cera e del sigillo, Aristotele aveva già intuito che anima e corpo non sono due cose unite, ma un'unica realtà vista da due prospettive. L'anima è la forma del corpo, e il corpo è la materia informata dall'anima. Questa visione immanente è alla radice di ogni successivo tentativo sistemico di superare il dualismo."),

    # Evoluzione come integrazione 11-20
    ("Gregory Bateson",
     "Perché si possa conseguire la grazia, le ragioni del cuore debbono essere integrate con le ragioni della ragione.",
     "Bateson, padre dell'ecologia della mente, usa il concetto di \"grazia\" per indicare uno stato di integrazione sistemica. Le \"ragioni del cuore\" (emozione, corpo, istinto) e le \"ragioni della ragione\" (logos, mente, pensiero) non sono in opposizione: l'evoluzione umana consiste nella loro integrazione. La \"mente ecologica\" di Bateson non è racchiusa nel cervello ma si estende al corpo e all'ambiente in un continuum circolare soma-psiche-ambiente."),
    ("Fritjof Capra",
     "In una visione sistemica, le proprietà essenziali di un organismo sono proprietà del tutto, che nessuna delle parti possiede.",
     "Capra, fisico e teorico dei sistemi, applica all'essere umano il principio secondo cui \"il tutto è più della somma delle parti\". Corpo, mente e anima non sono componenti da assemblare ma dimensioni di un unico sistema le cui proprietà emergono dall'interazione. L'evoluzione, in questa prospettiva, non è la somma di miglioramenti separati ma la trasformazione qualitativa del sistema nella sua totalità."),
    ("Osho",
     "Non sono contro il corpo, non sono contro la mente; sono per l'unità, una sinfonia, una sincronicità tra queste tre sfere. E un uomo sarà realizzato solo, completo solo, quando tutte e tre funzioneranno in totale armonia.",
     "Osho sintetizza in modo magistrale la visione sistemica: la realizzazione umana non consiste nel trascendere il corpo o la mente, ma nell'armonizzarli in una sinfonia. La sua figura di \"Zorba il Buddha\" incarna questa integrazione: la gioia del corpo (Zorba) e la consapevolezza dello spirito (Buddha) non sono in conflitto ma si potenziano a vicenda."),
    ("Andrew Taylor Still",
     "La persona è un'unità di corpo, mente e spirito; ogni corpo ha la capacità di mantenere il proprio stato di salute autoregolandosi.",
     "Still, medico del XIX secolo, fondò l'osteopatia su una visione sistemica ante litteram. L'essere umano è un'unità funzionale in cui corpo, mente e spirito interagiscono costantemente, e la salute è la capacità del sistema di autoregolarsi. La malattia, in questa prospettiva, non è l'invasione di un agente esterno ma la perdita di questa capacità integrata."),
    ("Fritjof Capra e Pier Luigi Luisi",
     "La vita è una trilogia tra mente, materia e processo.",
     "Nella loro opera \"Vita e natura\", Capra e Luisi propongono una visione della vita come processo sistemico in cui cognizione (mente), struttura (materia) e trasformazione (processo) sono inseparabili. Questa \"trilogia\" non è una gerarchia ma una rete di relazioni reciproche. L'evoluzione, in questa prospettiva, è il dispiegarsi di questa rete in livelli sempre più complessi di integrazione."),
    ("Pierre Teilhard de Chardin",
     "Noi non siamo esseri umani che vivono un'esperienza spirituale; siamo esseri spirituali che vivono un'esperienza umana.",
     "Il gesuita e paleontologo francese propone una visione evolutiva in cui la materia e lo spirito sono due aspetti di un unico processo cosmico. L'evoluzione non è solo biologica ma converge verso una sempre maggiore complessità e coscienza. In questa prospettiva sistemica, corpo, mente e anima sono dimensioni di un'unica traiettoria evolutiva che attraversa l'intero universo."),
    ("Ken Wilber",
     "L'evoluzione è la storia dell'aumento della profondità attraverso l'aumento della complessità.",
     "Wilber, teorico integrale, sintetizza in questa frase il principio evolutivo sistemico: l'evoluzione procede aumentando la complessità delle strutture (corpo, mente, società) e, simultaneamente, la profondità della coscienza (anima, spirito). Ogni livello emergente trascende e include i precedenti, in una gerarchia di totalità sempre più ampie. L'essere umano, in questa prospettiva, è un microcosmo di questo processo."),
    ("Ervin Laszlo",
     "L'universo è un sistema interconnesso in cui ogni parte riflette il tutto.",
     "Il filosofo della scienza ungherese, teorico dei sistemi, applica all'intero cosmo il principio olografico: ogni parte contiene l'informazione del tutto. In questa visione, corpo, mente e anima non sono solo uniti tra loro, ma sono espressione di un'unica realtà sistemica che li trascende e li include. L'evoluzione umana è parte dell'evoluzione cosmica."),
    ("Carl Gustav Jung",
     "Ogni incontro che fai è un incontro con te stesso.",
     "Jung esprime in modo folgorante il principio sistemico della circolarità: l'altro non è mai veramente \"altro\", ma una proiezione o un riflesso di dimensioni non riconosciute di sé. In ottica evolutiva, ogni relazione è un'opportunità di integrazione: ciò che vediamo fuori è ciò che dobbiamo integrare dentro. La psiche, come il corpo, è un sistema autoregolante che tende all'unità."),
    ("Rumi",
     "Non sei una goccia nell'oceano; sei l'oceano in una goccia.",
     "Il grande poeta mistico persiano esprime la visione sistemica nella sua forma più pura: l'essere umano non è una parte separata del tutto, ma il tutto che si manifesta in una forma particolare. Corpo, mente e anima non sono \"parti\" di te: sei tu nella tua totalità. L'evoluzione, in questa prospettiva, è il riconoscimento di questa identità profonda tra microcosmo e macrocosmo."),

    # Filosofi e pensatori sistemici
    ("Gregory Bateson",
     "Lo mostruoso è tentare di separare l'intelletto dalle emozioni, e considero ugualmente mostruoso tentare di separare la mente esterna da quella interna. O separare la mente dal corpo.",
     "Bateson, padre dell'ecologia della mente, definisce \"mostruosa\" ogni separazione tra le dimensioni dell'essere umano. La sua visione sistemica non si ferma al corpo individuale: la mente si estende all'ambiente, alle relazioni, al mondo. L'evoluzione, in questa prospettiva, consiste nel riconoscere che siamo parte di un sistema più ampio in cui ogni separazione è un'artificialità."),
    ("Gregory Bateson",
     "La realtà e la mia relazione con gli oggetti: io e la macchina da scrivere formiamo un sistema. La percezione abituale della mia pelle come limite ben definito tra me e il resto del mondo comincia a indebolirsi.",
     "Qui Bateson porta la visione sistemica alle sue estreme conseguenze: il confine del corpo non è un limite assoluto. La mente non è racchiusa nella pelle, ma si estende nelle relazioni e negli strumenti che utilizziamo. L'evoluzione umana è l'ampliamento di questa consapevolezza ecologica."),
    ("Tommaso Campanella",
     "Lo spirito forma il corpo e lo distingue nelle sue parti... l'anima immortale perfeziona tutto l'artificio e le sue operazioni. E insieme si fa forma di tutto l'uomo.",
     "Il filosofo rinascimentale elabora una visione in cui lo spirito (forza vitale) e l'anima (principio immortale) non sono separati dal corpo, ma ne costituiscono la forma. L'anima \"si fa forma di tutto l'uomo\", cioè non abita un corpo già formato, ma lo plasma dall'interno. Una concezione precorritrice dell'unità psicofisica."),
    ("Edgar Morin",
     "Lo spirito è un'emergenza propria dello sviluppo cerebrale di homo sapiens, ma solo nelle condizioni culturali di apprendimento e comunicazione unite al linguaggio umano.",
     "Morin, teorico della complessità, colloca lo spirito nel processo evolutivo: non è un'entità separata che \"abita\" il cervello, ma un'emergenza del sistema cervello-cultura-linguaggio. L'evoluzione umana è multidimensionale: biologica, cognitiva, culturale e spirituale insieme."),
    ("Edgar Morin",
     "L'idea di Elohim unisce e traduce in sé, in modo indistinto, l'idea di turbinio genesiaco, l'idea di potere creatore e l'idea di processo organizzatore.",
     "Morin reinterpreta la divinità creatrice come principio sistemico: creazione, organizzazione e trasformazione sono aspetti di un unico processo. In questa visione, materia e spirito non sono opposti ma dimensioni di un unico flusso auto-organizzantesi."),

    # Fisici (seconda serie): Bohm x2 dup + Heisenberg + Schrödinger x3
    ("David Bohm",
     "Il pensiero è un sistema. Non solo include pensiero e sentimenti, ma include lo stato del corpo; include l'intera società... Non si può spezzare questo processo, perché è tutto un unico processo.",
     "Bohm applica esplicitamente il concetto di sistema all'essere umano: corpo, mente e società sono parti interdipendenti di un unico sistema. La separazione tra \"il mio pensiero\" e \"il tuo pensiero\", tra \"la mia mente\" e \"il mio corpo\", è fuorviante perché non riconosce la natura sistemica della realtà."),
    ("Werner Heisenberg",
     "Comprendere significa essere in possesso di rappresentazioni e concetti necessari per riconoscere che una moltitudine di fenomeni differenti fa parte di un tutto coerente... ridurre il molteplice all'uno.",
     "Il padre dell'indeterminazione quantistica definisce la comprensione stessa come un atto di unificazione: capire significa vedere il molteplice come manifestazione dell'uno. Applicato all'essere umano, questo significa che comprendere la salute e la malattia richiede di vedere corpo, mente e anima come espressioni di un'unica totalità."),
    ("Erwin Schrödinger",
     "Quella unità di conoscenza, di sentimento e di scelta che consideri come TUA non è nata dal nulla pochi anni fa. In realtà, questa conoscenza, questo sentimento e questa scelta sono, nella loro essenza, eterni, immutabili e numericamente UNI in tutti gli uomini e in tutti gli esseri viventi.",
     "Schrödinger, premio Nobel per la fisica, elabora una visione in cui la coscienza individuale non è un frammento separato, ma manifestazione di un'unica coscienza universale. L'evoluzione, in questa prospettiva, non è l'accumulo di conoscenze individuali, ma il riconoscimento di questa unità fondamentale."),
    ("Erwin Schrödinger",
     "Colui che è immerso nell'Atman pienamente lucido non conosce differenza tra mondo interno ed esterno. È nello stato di beatitudine in cui ogni desiderio è soddisfatto.",
     "Schrödinger trova nella filosofia vedantica una conferma della sua intuizione scientifica: la separazione tra interno ed esterno, tra sé e mondo, tra corpo e spirito, è un'illusione (Maya). La scienza stessa, portata alle sue estreme conseguenze, dissolve questa separazione."),
    ("Erwin Schrödinger",
     "Quella che sembra essere una pluralità è meramente una serie di aspetti di una sola cosa, prodotta dall'illusione (la Maya indiana).",
     "Questa è forse la formulazione più radicale della visione sistemica: la molteplicità delle menti, dei corpi, delle anime è un'illusione prospettica. L'evoluzione della coscienza consiste nel riconoscere questa unità al di là delle apparenze."),

    # Maestri (Iyengar + Perls + Capra)
    ("B.K.S. Iyengar",
     "Lo yoga è come la musica: il ritmo del corpo, la melodia della mente e l'armonia dell'anima creano la sinfonia della vita.",
     "Il grande maestro di yoga utilizza la metafora musicale per esprimere l'unità sistemica: corpo, mente e anima non sono tre strumenti separati, ma tre dimensioni di un'unica sinfonia. L'evoluzione, in questa prospettiva, è l'accordatura che permette loro di risuonare insieme."),
    ("B.K.S. Iyengar",
     "Non puoi individuare dove finisce il corpo e dove inizia la mente, dove finisce la mente e inizia il Sé.",
     "Iyengar esprime in modo diretto il principio sistemico: i confini tra corpo, mente e Sé sono costruzioni arbitrarie. La pratica yoga non serve a \"unire\" ciò che è separato, ma a riconoscere un'unità che è sempre stata presente."),
    ("B.K.S. Iyengar",
     "La salute è uno stato di completa armonia di corpo, mente e spirito. Quando si è liberi da disabilità fisiche e distrazioni mentali, le porte dell'anima si aprono.",
     "Per Iyengar, la salute non è l'assenza di malattia ma uno stato di armonia sistemica. Le \"porte dell'anima\" non si aprono grazie a una pratica puramente spirituale, ma attraverso l'integrazione di corpo, mente e spirito in un'unica totalità funzionante."),
    ("Frederick Perls",
     "Il trattamento isolato degli aspetti della personalità umana rafforza il modo di pensare in termini di magia, e sostiene la credenza che l'anima e il corpo siano due cose isolate tenute insieme da qualcosa di misterioso.",
     "Perls, fondatore della Gestalt, denuncia la separazione come una forma di pensiero magico: credere che anima e corpo siano due sostanze separate è un residuo di mentalità pre-scientifica. L'organismo umano è un tutto vivente che si esprime attraverso aspetti che chiamiamo corpo, mente e anima."),
    ("Fritjof Capra",
     "Una società sostenibile deve essere disegnata in modo tale che le sue modalità di vita, affari, economia e strutture fisiche e tecnologiche siano tali da non interferire con la capacità intrinseca della Natura di sostenere la vita.",
     "Capra estende la visione sistemica dall'individuo alla società e all'ecosistema: la salute del corpo-mente-anima individuale è inseparabile dalla salute del sistema sociale e naturale di cui facciamo parte. L'evoluzione umana, in questa prospettiva, è l'armonizzazione del nostro modo di vivere con i sistemi più ampi che ci sostengono."),
]

print(f"Total citations to import: {len(CITATIONS)}")

# ---------------- LLM prompt ----------------

SYSTEM_PROMPT = (
    "Sei un redattore editoriale esperto di filosofia, spiritualità, psicologia, fisica quantistica, "
    "medicina integrata e visione sistemica. "
    "Scrivi in italiano fluente, elegante e profondo, con un tono divulgativo ma colto. "
    "Ti verrà fornita una citazione di un autore e un commento introduttivo. "
    "Il tuo compito è produrre una INTEGRAZIONE originale di CIRCA 400 PAROLE "
    "(obbligatoriamente tra 380 e 460 parole) che AMPLIFICHI il commento con: "
    "riferimenti alla vita e all'opera dell'autore, connessioni con altri pensatori, "
    "esempi concreti, implicazioni pratiche per la crescita personale, "
    "risonanze con la visione sistemica corpo-mente-anima. "
    "Non ripetere frasi del commento; sviluppa in modo complementare. "
    "Suddividi in 3 paragrafi fluidi separati da DOPPIO A CAPO. "
    "Non usare titoli, elenchi puntati, grassetti o Markdown. "
    "Non citare siti web né firmarti. "
    "Devi inoltre proporre un TITOLO evocativo per l'articolo in italiano "
    "(non ripetere la citazione, non citare l'autore nel titolo). "
    "Rispondi SOLO con JSON valido: "
    '{"title": "<titolo>", "expansion": "<integrazione 400 parole in 3 paragrafi>"}'
)


def clean_json_response(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```\s*$", "", raw)
    return raw.strip()


async def generate(author: str, quote: str, commento: str) -> dict | None:
    from emergentintegrations.llm.chat import LlmChat, UserMessage
    prompt = (
        f"Autore: {author}\n"
        f"Citazione: «{quote}»\n"
        f"Commento introduttivo esistente (NON ripeterlo, sviluppalo in modo complementare):\n"
        f"{commento}\n\n"
        f"Produci ora il JSON con titolo ed integrazione (~400 parole)."
    )
    chat = LlmChat(
        api_key=EMERGENT_LLM_KEY,
        session_id=str(uuid.uuid4()),
        system_message=SYSTEM_PROMPT,
    ).with_model("anthropic", "claude-sonnet-4-5-20250929")
    try:
        response = await chat.send_message(UserMessage(text=prompt))
    except Exception as e:
        print(f"  LLM ERROR: {e}")
        return None
    raw = clean_json_response(response or "")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if not m:
            return None
        try:
            data = json.loads(m.group(0))
        except Exception:
            return None
    title = (data.get("title") or "").strip().strip('"')
    expansion = (data.get("expansion") or "").strip()
    if not title or not expansion:
        return None
    return {"title": title, "expansion": expansion}


def build_summary(author: str, quote: str, commento: str, expansion: str) -> str:
    # Article body: quote block + commentary + expansion
    return (
        f"«{quote}»\n"
        f"— {author}\n\n"
        f"{commento}\n\n"
        f"{expansion}"
    )


def unique_source(author: str, quote: str) -> str:
    """Synthetic source id used for idempotency (no external URL)."""
    h = hashlib.md5(f"{author}|{quote[:120]}".encode("utf-8")).hexdigest()[:16]
    return f"citazioni-docx:{h}"


async def process(db, entry, idx: int, sem: asyncio.Semaphore):
    async with sem:
        author, quote, commento = entry
        src = unique_source(author, quote)
        # idempotency
        existing = await db.articles.find_one({"source_url": src})
        if existing:
            print(f"[{idx:02d}] SKIP {author} — {quote[:50]}")
            return
        result = None
        for _ in range(3):
            result = await generate(author, quote, commento)
            if result:
                wc = len(result["expansion"].split())
                if 350 <= wc <= 520:
                    break
        if not result:
            print(f"[{idx:02d}] FAIL {author}")
            return
        summary = build_summary(author, quote, commento, result["expansion"])
        category, image = author_meta(author)
        doc = {
            "id": str(uuid.uuid4()),
            "title": result["title"],
            "summary": summary,
            "category": category,
            "source_url": src,
            "image_url": image,
            "is_premium": False,
            "views": 0,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "expanded_at": datetime.now(timezone.utc).isoformat(),
        }
        await db.articles.insert_one(doc)
        wc_total = len(summary.split())
        print(f"[{idx:02d}] OK [{category}] {wc_total}w — {author}: {result['title']}")


async def main():
    if not EMERGENT_LLM_KEY:
        print("Missing EMERGENT_LLM_KEY")
        return
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    sem = asyncio.Semaphore(4)
    await asyncio.gather(*[process(db, e, i+1, sem) for i, e in enumerate(CITATIONS)])
    total = await db.articles.count_documents({})
    print(f"\nTotal DB articles: {total}")


if __name__ == "__main__":
    asyncio.run(main())
